In [1]:
import tensorflow as tf
import os
from tensorflow import keras
import keras_preprocessing as kp
import cv2
import imghdr

C:\Users\thedu\AppData\Local\Temp\ipykernel_1308\1196589625.py:6: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
  import imghdr


In [2]:
os.listdir('AIandRealArt/train/')
data_loc = 'AIandRealArt/train/'

In [3]:
import numpy as np
from matplotlib import  pyplot as plt

In [4]:
data = tf.keras.preprocessing.image_dataset_from_directory(data_loc,shuffle =True)

Found 18618 files belonging to 2 classes.


In [5]:
data_scaled = data.map(lambda x,y :((x/255),y))
scaled_it = data_scaled.as_numpy_iterator()
batch_scaled = scaled_it.next()
batch_scaled[0]

array([[[[0.42352942, 0.5019608 , 0.3745098 ],
         [0.4372549 , 0.49803922, 0.3627451 ],
         [0.46960783, 0.49117646, 0.35196078],
         ...,
         [0.36568627, 0.42843136, 0.28333333],
         [0.32254902, 0.39313725, 0.24411765],
         [0.3647059 , 0.44705883, 0.29411766]],

        [[0.38431373, 0.46372548, 0.33333334],
         [0.40098038, 0.4598039 , 0.3254902 ],
         [0.4392157 , 0.47058824, 0.327451  ],
         ...,
         [0.42156863, 0.48235294, 0.3382353 ],
         [0.4117647 , 0.48039216, 0.33235294],
         [0.45882353, 0.5294118 , 0.38039216]],

        [[0.3647059 , 0.44019607, 0.3019608 ],
         [0.3735294 , 0.42745098, 0.28921568],
         [0.40490195, 0.43823528, 0.28529412],
         ...,
         [0.46078432, 0.5156863 , 0.3735294 ],
         [0.4598039 , 0.5205882 , 0.3764706 ],
         [0.47549018, 0.5382353 , 0.39313725]],

        ...,

        [[0.7852941 , 0.66568625, 0.5647059 ],
         [0.8098039 , 0.69411767, 0.5980392 ]

In [6]:
train_size = int(len(data_scaled)*0.7)
val_size = int(len(data_scaled)*0.1)+1
test_size = int(len(data_scaled)*0.2)+1
train_size+val_size+test_size

583

In [7]:
train = data_scaled.take(train_size)
test = data_scaled.skip(train_size).take(test_size)
validation = data_scaled.skip(train_size).skip(test_size).take(val_size)

In [8]:
model = tf.keras.models.load_model('my_model.keras')

In [9]:
labels = []
predictions = []

In [10]:
for x, y in test.as_numpy_iterator():
    labels.append(y)
    pr = model.predict(x)
    predictions.append(np.argmax(pr, axis=1)) 

1/1 [==============================] - 1s 695ms/step


In [11]:
labels = np.concatenate(labels)
predictions = np.concatenate(predictions)

In [12]:
labels

array([0, 0, 0, ..., 1, 0, 0])

In [13]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
len(predictions) 

3744

In [15]:
conf_matrix = tf.math.confusion_matrix(labels, predictions, num_classes=None, weights=None, dtype=tf.dtypes.int32, name=None)

In [16]:
print(conf_matrix)

tf.Tensor(
[[2094    0]
 [1650    0]], shape=(2, 2), dtype=int32)
